spark.sql.catalogImplementation                         hive
spark.sql.warehouse.dir                                /Users/jguerrrero/code/jguerrero_personal/.local/spark/warehouse
spark.hadoop.javax.jdo.option.ConnectionURL            jdbc:derby:;databaseName=/Users/jguerrrero/code/jguerrero_personal/.local/spark/metastore_db;create=true
spark.hadoop.javax.jdo.option.ConnectionDriverName     org.apache.derby.jdbc.EmbeddedDriver
spark.hadoop.datanucleus.schema.autoCreateAll          true
spark.hadoop.hive.metastore.schema.verification        false
spark.sql.legacy.createHiveTableByDefault              false
